version: '3.9'

services:
  db:
    container_name: social_network_db
    image: postgres:latest
    volumes:
      - ./src/database/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - DB_NAME=social_network_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
